# Generated by Django 4.1.4 on 2022-12-24 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='Images')),
                ('description', models.TextField()),
                ('upload_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='sign',
        ),
    ]
