# Generated by Django 4.1.4 on 2022-12-24 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_index'),
    ]

    operations = [
        migrations.DeleteModel(
            name='index',
        ),
    ]
