# Generated by Django 4.1.4 on 2023-01-01 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0005_alter_details_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
